# default configuration

baseURL = "/"
title   = "Hugo Theme: hugo-pure"

languageCode   = "en-us"
hasCJKLanguage = true

[markup]
_merge    = "deep"
[markup.highlight]
_merge    = "deep"
noClasses = false
[markup.tableOfContents]
_merge    = "deep"
endLevel  = 2

[menus]

[[menus.main]]
identifier = "home"
name       = "Home"
pageRef    = "/"
weight     = 1

[[menus.footer]]
identifier  = "rss"
name        = "Feed"
pageRef     = "/"
weight      = 5
[menus.footer.params]
targetBlank = true
format      = "rss"

#[params]
#doubleColumns = true

#[outputFormats]
#[outputFormats.myjson]
#baseName  = "myfilename"
#mediaType = "application/json"
#[outputs]
#home = ["html", "rss", "myjson"]

